# Generated by Django 4.1.5 on 2023-03-21 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aza',
            name='name',
            field=models.CharField(default=True, max_length=500),
            preserve_default=False,
        ),
    ]
